name: CI & Deploy

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  vitest:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup environment
      run: bash scripts/setup.sh
    - name: Run Vitest Tests
      run: pnpm test

  cypress:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup environment
        run: bash scripts/setup.sh
      - name: Install Cypress Binary
        run: npx cypress install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm preview --port 5173

  build:
    runs-on: ubuntu-22.04
    needs: [vitest] # , cypress
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup environment
        run: bash scripts/setup.sh
      - name: build environment
        run: pnpm build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build

    permissions:
      pages: write   
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
