name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  setup:
    runs-on: &runs_on ubuntu-latest
    steps:
      - &default-checkout
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Setup Environment
          run: bash scripts/setup.sh
  vitest:
    needs: setup
    runs-on: *runs_on
    steps:
      - *default-checkout
      - name: Run Vitest Tests
        run: pnpm test

  cypress:
    needs: setup
    runs-on: *runs_on
    steps:
      - *default-checkout
      - name: Run Cypress Tests
        run: pnpm cypress:run

  build-deploy:
    runs-on: *runs_on
    needs: [vitest, cypress]
    steps:
      - *default-checkout
      - name: Deploy to GitHub Pages
        run: pnpm deploy
        env:
          GHPAGES_TOKEN: ${{ secrets.GHPAGES_TOKEN }}
