name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

# Define a common anchor for the checkout step
x-checkout: &default-checkout
  - name: Checkout Repository
    uses: actions/checkout@v3
  - name: Setup Environment
    run: bash scripts/setup.sh

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - *default-checkout
      - name: Run Vitest Tests
        run: pnpm test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - *default-checkout
      - name: Run Cypress Tests
        run: pnpm cypress:run

  build-deploy:
    runs-on: ubuntu-latest
    needs: [vitest, cypress]
    steps:
      - *default-checkout
      - name: Deploy to GitHub Pages
        run: pnpm deploy
        env:
          GHPAGES_TOKEN: ${{ secrets.GHPAGES_TOKEN }}
