name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  setup:
    runs-on: &runs_on ubuntu-latest
    steps:
      - &default-checkout
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Setup Environment
          run: bash scripts/setup.sh
  vitest:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: setup environment
      run: bash scripts/setup.sh
    - name: Run Vitest Tests
      run: pnpm test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup environment
        run: bash scripts/setup.sh
      - name: Run Cypress Tests
        run: pnpm cypress:run

  build-deploy:
    runs-on: ubuntu-latest
    needs: [vitest, cypress]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup environment
        run: bash scripts/setup.sh
      - name: Deploy to GitHub Pages
        run: pnpm deploy
        env:
          GHPAGES_TOKEN: ${{ secrets.GHPAGES_TOKEN }}
