name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Composite Action
        uses: ./.github/actions/setup.yml
      - name: Run Vitest Tests
        run: pnpm test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Composite Action
        uses: ./.github/actions/setup.yml
      - name: Run Cypress Tests
        run: pnpm cypress:run

  build-deploy:
    runs-on: ubuntu-latest
    needs: [vitest, cypress]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Composite Action
        uses: ./.github/actions/setup.yml
      - name: Deploy to GitHub Pages
        run: pnpm deploy
        env:
          GHPAGES_TOKEN: ${{ secrets.GHPAGES_TOKEN }}
